# -*- mode: ruby -*-
# vi: set ft=ruby :

load "Vagrantfile_local"

# Configure using Vagrant spec version 2
Vagrant.configure(2) do |config|
  # See https://docs.vagrantup.com.

  # ============================================================================
  #                                                                  OVERALL BOX
  # ============================================================================

  # To specify a pre-defined box in the cloud, just name the box.
  config.vm.box = BASE_IMAGE
  # To use a local ISO, specify a box of "base"
  # config.vm.box = "base"
  # config.vm.box_url = "file:///...../my_favorite_image.iso"

  # Optionally, give the box an alias
  config.vm.define MACHINE_NAME

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false


  # ============================================================================
  #                                                      NETWORKING (SSH, PORTS)
  # ============================================================================

  # ###########################################   SSH (e.g. for remote debugging)

  config.ssh.username = SSH_USER_ACCOUNT
  # Prevent Vagrant from generating a random key
  config.ssh.insert_key = false

  # Tell Vagrant to use our existing key (after first connecting with the default insecure_private_key)
  config.ssh.private_key_path = [SSH_PRIVATE_KEY, "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: SSH_PUBLIC_KEY, destination: "~/.ssh/authorized_keys"

  # Prevent SSH access with a plaintext password
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo service ssh restart
  EOC

  # ###########################################   HTTP

  config.vm.network "forwarded_port", guest: 80, host: 9080 # http://localhost:9080

  # ###########################################   CUSTOM PORTS FOR WHATEVER

  # config.vm.network "forwarded_port", host: 9000, guest: 9000, auto_correct: true
  # config.vm.network "forwarded_port", host: 9001, guest: 9001, auto_correct: true
  # config.vm.network "forwarded_port", host: 9002, guest: 9002, auto_correct: true

 
  # ============================================================================
  #                                                      HOW THE BOX IS LAUNCHED
  # ============================================================================

  config.vm.synced_folder WORK_FOLDER, WORK_FOLDER_SHARED_AS 
  config.vm.synced_folder DROP_FOLDER, DROP_FOLDER_SHARED_AS, create: true
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant",  group: "vagrant" 
  config.vm.synced_folder "../scripts_library", "/scripts_library", owner: "vagrant",  group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = not(HEADLESS)
    # vb.memory = "1024"
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
